name = "NoobCraft"
author = "DeliusVDB"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3132dc3924bfc87d76e25480624554a470de43a9ab7697e267cf885cc9344692"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
