name = "NoobCraft"
author = "DeliusVDB"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4379678ef1d3fe1ec2602284e150344551271100a04d92e0d3cbbf1bc20f2a0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
