name = "NoobCraft"
author = "DeliusVDB"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2957f8322c41ca98d5102ac681fbd9e756978036a1d138ee3950c8ab2610a0d3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
